name: optibox-frontend

services:
  keycloak:
    image: keycloak/keycloak:latest
    container_name: optibox-keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
      - ./moyens-levage-realm.json:/opt/keycloak/data/import/moyens-levage-realm.json
    command: [ "start-dev", "--import-realm" ]

  angular-app:
    build: .
    container_name: angular-app
    ports:
      - "4200:4200"
    networks:
      - optibox-shared-network

networks:
  optibox-shared-network:
    external: true
