name: optibox-frontend

services:
  angular-app:
    build: .
    container_name: angular-app
    ports:
      - "4200:4200"
    networks:
      - optibox-shared-network

networks:
  optibox-shared-network:
    external: true
